# Analysis of Results

In [1]:
import pandas as pd
import json
from pathlib import Path
from dataclasses import dataclass
import matplotlib.pyplot as plt
import numpy as np
import csv
from dotenv import load_dotenv
import os
import qvarnet
load_dotenv()  # Load environment variables from .env file
print(os.getcwd())
if os.getenv('MOUNTPOINT') is None:
    raise ValueError("MOUNTPOINT environment variable is not set.")
import utils

/home/pfargas/Desktop/PhD/data_analysis

## Change to the directory where the results are stored

In [2]:
os.chdir(os.getenv('MOUNTPOINT'))

## Data loading and processing

### Loading results in a dataframe

In [7]:
def load_results(parquet_dir:str, parquet_name: str, data_path:str) -> pd.DataFrame:
    if parquet_name not in os.listdir(parquet_dir):
        df = utils.load_simulation_results(data_path)
        df.to_parquet(parquet_dir+"/"+parquet_name, engine="fastparquet")
    else:
        df = pd.read_parquet(parquet_dir+"/"+parquet_name, engine="fastparquet")
    return df

In [8]:
PARQUET_DIR = "/home/pfargas/Desktop/PhD/data_analysis"

df_zero_walkers = load_results(PARQUET_DIR, "results_ZERO_WALKERS.parquet", './out/20260225_123439')
df_normal_walkers = load_results(PARQUET_DIR, "results.parquet", './out/20260211_142926')

df_zero_walkers.head()

,seed,total_energy,std,training_time_seconds,best_score,path,model_type,model_architecture,model_activation,training_batch_size,training_num_epochs,sampler_type,sampler_step_size,sampler_chain_length,sampler_PBC,optimizer_type,optimizer_learning_rate
0,42,38.690849,9.106707,401.942217,56.904263,out/20260225_123439/config_64_hu_3_l_100_parti...,exponential-mlp-fourth-decay,"[100, 64, 64, 64, 1]",tanh,1000,5000,metropolis_hastings,0.05,125,20,adam,0.01
1,42,134.062271,15.575247,354.043097,165.212769,out/20260225_123439/config_64_hu_2_l_200_parti...,exponential-mlp-fourth-decay,"[200, 64, 64, 1]",tanh,500,5000,metropolis_hastings,0.10,125,20,adam,0.01
2,42,75.269241,16.169909,428.847117,107.609055,out/20260225_123439/config_32_hu_2_l_200_parti...,exponential-mlp-fourth-decay,"[200, 32, 32, 1]",tanh,1000,5000,metropolis_hastings,0.05,125,20,adam,0.01
3,42,38.597145,8.980019,204.885929,56.557182,out/20260225_123439/config_64_hu_3_l_100_parti...,exponential-mlp-fourth-decay,"[100, 64, 64, 64, 1]",tanh,500,5000,metropolis_hastings,0.05,125,20,adam,0.01
4,42,-0.086774,0.000000,394.899219,-0.086774,out/20260225_123439/config_128_hu_3_l_50_parti...,exponential-mlp-fourth-decay,"[50, 128, 128, 128, 1]",tanh,1000,5000,metropolis_hastings,0.05,125,20,adam,0.01

In [9]:
df_normal_walkers.head()

,seed,total_energy,std,training_time_seconds,best_score,path,model_type,model_architecture,model_activation,training_batch_size,training_num_epochs,sampler_type,sampler_step_size,sampler_chain_length,sampler_PBC,optimizer_type,optimizer_learning_rate
0,42,21.395267,3.152891,38.339563,27.701050,out/20260211_142926/config_8_hu_3_l_50_particl...,exponential-mlp-fourth-decay,"[50, 8, 8, 8, 1]",tanh,500,5000,metropolis_hastings,0.05,100,20,adam,0.001
1,42,5.650299,1.682009,27.508885,9.014318,out/20260211_142926/config_4_hu_3_l_10_particl...,exponential-mlp-fourth-decay,"[10, 4, 4, 4, 1]",tanh,1000,5000,metropolis_hastings,0.50,125,20,adam,0.001
2,42,4.518309,1.176057,16.415093,6.870423,out/20260211_142926/config_4_hu_1_l_10_particl...,exponential-mlp-fourth-decay,"[10, 4, 1]",tanh,500,5000,metropolis_hastings,0.05,125,20,adam,0.010
3,42,4.970542,1.889289,18.872814,8.749120,out/20260211_142926/config_8_hu_1_l_10_particl...,exponential-mlp-fourth-decay,"[10, 8, 1]",tanh,1000,5000,metropolis_hastings,0.05,150,20,adam,0.001
4,42,25.625671,2.646152,219.222425,30.917974,out/20260211_142926/config_32_hu_1_l_200_parti...,exponential-mlp-fourth-decay,"[200, 32, 1]",tanh,500,5000,metropolis_hastings,0.05,150,20,adam,0.001

### Cleaning and transforming the data

In [10]:
df_zero_walkers = utils.separate_input_dim_and_hidden_dim(df_zero_walkers)
df_zero_walkers = utils.add_energy_per_particle(df_zero_walkers)
df_zero_walkers = utils.clean_non_informative_columns(df_zero_walkers)

df_normal_walkers = utils.separate_input_dim_and_hidden_dim(df_normal_walkers)
df_normal_walkers = utils.add_energy_per_particle(df_normal_walkers)
df_normal_walkers = utils.clean_non_informative_columns(df_normal_walkers)

Column 'seed' has only 1 unique group size, dropping.
Column 'model_type' has only 1 unique group size, dropping.
Column 'model_activation' has only 1 unique group size, dropping.
Column 'training_num_epochs' has only 1 unique group size, dropping.
Column 'sampler_type' has only 1 unique group size, dropping.
Column 'sampler_PBC' has only 1 unique group size, dropping.
Column 'optimizer_type' has only 1 unique group size, dropping.
Column 'seed' has only 1 unique group size, dropping.
Column 'model_type' has only 1 unique group size, dropping.
Column 'model_activation' has only 1 unique group size, dropping.
Column 'training_num_epochs' has only 1 unique group size, dropping.
Column 'sampler_type' has only 1 unique group size, dropping.
Column 'sampler_PBC' has only 1 unique group size, dropping.
Column 'optimizer_type' has only 1 unique group size, dropping.

In [11]:
df_normal_walkers.head()

,total_energy,std,training_time_seconds,best_score,path,training_batch_size,sampler_step_size,sampler_chain_length,optimizer_learning_rate,input_dim,hidden_dim,energy_per_particle,std_energy_per_particle,best_score_per_particle
0,21.395267,3.152891,38.339563,27.701050,out/20260211_142926/config_8_hu_3_l_50_particl...,500,0.05,100,0.001,50,"[8, 8, 8]",0.427905,0.063058,0.554021
1,5.650299,1.682009,27.508885,9.014318,out/20260211_142926/config_4_hu_3_l_10_particl...,1000,0.50,125,0.001,10,"[4, 4, 4]",0.565030,0.168201,0.901432
2,4.518309,1.176057,16.415093,6.870423,out/20260211_142926/config_4_hu_1_l_10_particl...,500,0.05,125,0.010,10,[4],0.451831,0.117606,0.687042
3,4.970542,1.889289,18.872814,8.749120,out/20260211_142926/config_8_hu_1_l_10_particl...,1000,0.05,150,0.001,10,[8],0.497054,0.188929,0.874912
4,25.625671,2.646152,219.222425,30.917974,out/20260211_142926/config_32_hu_1_l_200_parti...,500,0.05,150,0.001,200,[32],0.128128,0.013231,0.154590

In [12]:
df_zero_walkers.head()

,total_energy,std,training_time_seconds,best_score,path,training_batch_size,sampler_step_size,sampler_chain_length,optimizer_learning_rate,input_dim,hidden_dim,energy_per_particle,std_energy_per_particle,best_score_per_particle
0,38.690849,9.106707,401.942217,56.904263,out/20260225_123439/config_64_hu_3_l_100_parti...,1000,0.05,125,0.01,100,"[64, 64, 64]",0.386908,0.091067,0.569043
1,134.062271,15.575247,354.043097,165.212769,out/20260225_123439/config_64_hu_2_l_200_parti...,500,0.10,125,0.01,200,"[64, 64]",0.670311,0.077876,0.826064
2,75.269241,16.169909,428.847117,107.609055,out/20260225_123439/config_32_hu_2_l_200_parti...,1000,0.05,125,0.01,200,"[32, 32]",0.376346,0.080850,0.538045
3,38.597145,8.980019,204.885929,56.557182,out/20260225_123439/config_64_hu_3_l_100_parti...,500,0.05,125,0.01,100,"[64, 64, 64]",0.385971,0.089800,0.565572
4,-0.086774,0.000000,394.899219,-0.086774,out/20260225_123439/config_128_hu_3_l_50_parti...,1000,0.05,125,0.01,50,"[128, 128, 128]",-0.001735,0.000000,-0.001735

In [ ]:
def aggregate_data(list_df: list[pd.DataFrame], groupby_cols: list[str], agg_col: str, agg_func: str) -> pd.DataFrame:
    """
    Aggregates the data by grouping by the specified columns and applying the specified aggregation function to the specified column.

    Args:
        list_df (list[pd.DataFrame]): List of DataFrames to aggregate.
        groupby_cols (list[str]): List of column names to group by.
        agg_col (str): Column name to apply the aggregation function to.
        agg_func (str): Aggregation function to apply (e.g., 'mean', 'median', 'std').

    Returns:
        pd.DataFrame: Aggregated DataFrame.
    """
    # Concatenate all DataFrames in the list
    combined_df = pd.concat(list_df, ignore_index=True)
    
    # Group by the specified columns and apply the aggregation function
    aggregated_df = combined_df.groupby(groupby_cols)[agg_col].agg(agg_func).reset_index()
    
    return aggregated_df

## Data visualization and analysis

In [ ]:
test_row = utils.localize_element_in_dataframe(df, 10, "[64, 64]", 0.01, 150, 0.5)
current_path = test_row['path']
print(current_path)

In [ ]:
energy_history = utils.get_energy_history(current_path.iloc[0])
plt.plot(energy_history)

In [ ]:
model, jax_params, input_dim = utils.load_model_from_path(current_path.iloc[0])
print(model)

In [ ]:
utils.plot_wavefunction_one_particle(model, jax_params, input_dim)

In [ ]:
test_row.iloc[0]